name: Update README with GitHub Activity

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:       # Allow manual trigger
  push:
    branches: [ master ]   # Run on push to master for testing

permissions:
  contents: write         # Write permission to commit to repository

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update README with recent GitHub activity
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
      
      - name: Update README with GitHub Activity
        uses: ./
        with:
          USERNAME: ${{ github.repository_owner }}
          MAX_LINES: '5'
          COMMIT_MSG: '🚀 Update README with latest GitHub activity'
        env:
          ACTIVITY_TOKEN: ${{ secrets.ACTIVITY_TOKEN }}